art_sky = [[
    {key: '0', time: 4},
    {key: '0', time: 4},
    {key: 'H', time: 4},
    {key: 'J', time: 4},

    {key: 'Q', time: 6},
    {key: 'J', time: 2},
    {key: 'Q', time: 4},
    {key: 'E', time: 4},

    {key: 'J', time: 4},
    {key: '0', time: 4},
    {key: '0', time: 4},
    {key: 'D', time: 4},
    {key: 'H', time: 6},
    {key: 'G', time: 2},
    {key: 'H', time: 4},
    {key: 'Q', time: 4},
    {key: 'G', time: 4},

    {key: '0', time: 4},
    {key: '0', time: 4},

    {key: 'F', time: 2},
    {key: 'D', time: 2},
    {key: 'F', time: 6},
    {key: 'D', time: 2},
    {key: 'F', time: 4},
    {key: 'Q', time: 4},
    {key: 'D', time: 4},

    {key: '0', time: 6},
    {key: 'Q', time: 2},
    {key: 'Q', time: 2},
    {key: 'Q', time: 2},
    {key: 'J', time: 4},
     {key: '0', time: 2},

     {key: 'F', time: 2},
    {key: 'F', time: 4},
    {key: 'J', time: 4},
    //
    {key: 'H', time: 4},
    {key: '0', time: 4},
    {key: '0', time: 4},
    {key: 'H', time: 2},
    {key: 'J', time: 2},

    {key: 'Q', time: 6},
    {key: 'J', time: 2},
    {key: 'Q', time: 4},
    {key: 'E', time: 4},

    {key: 'J', time: 4},
    {key: '0', time: 4},
    {key: '0', time: 4},
    {key: 'D', time: 2},
    {key: 'D', time: 2},

    {key: 'H', time: 6},
    {key: 'G', time: 2},
    {key: 'H', time: 4},
    {key: 'Q', time: 4},

    {key: 'G', time: 4},
    {key: '0', time: 4},
    {key: '0', time: 4},
    {key: 'D', time: 4},

    {key: 'F', time: 4},
    {key: 'Q', time: 2},
    {key: 'J', time: 2},
    {key: '0', time: 4},
    {key: 'Q', time: 4},

    {key: 'W', time: 4},
    {key: 'E', time: 2},
    {key: 'Q', time: 2},
    {key: '0', time: 4},
    {key: '0', time: 4},

    {key: 'Q', time: 2},
    {key: 'J', time: 2},
    {key: 'H', time: 4},
    {key: 'J', time: 4},
    {key: 'G', time: 4},

    {key: 'H', time: 4},
    {key: '0', time: 4},
    {key: '0', time: 4},
    {key: 'Q', time: 2},
    {key: 'W', time: 2},

    {key: 'E', time: 6},
    {key: 'W', time: 2},
    {key: 'E', time: 4},
    {key: 'T', time: 4},

    {key: 'W', time: 4},
    {key: '0', time: 4},
    {key: '0', time: 4},
    {key: 'G', time: 2},
    {key: 'G', time: 2},

    {key: 'Q', time: 6},
    {key: 'J', time: 2},
    {key: 'Q', time: 4},
    {key: 'E', time: 4},

    {key: 'E', time: 4},
    {key: 'E', time: 4},
    {key: 'E', time: 4},
    {key: 'E', time: 4},

    {key: 'H', time: 2},
    {key: 'J', time: 2},
    {key: 'Q', time: 4},
    {key: 'J', time: 2},
    {key: 'Q', time: 2},
    {key: 'W', time: 4},

    {key: 'Q', time: 6},
    {key: 'G', time: 2},
    {key: 'G', time: 4},
    {key: '0', time: 4},

    {key: 'R', time: 4},
    {key: 'E', time: 4},
    {key: 'W', time: 4},
    {key: 'Q', time: 4},

    {key: 'E', time: 4},
    {key: 'E', time: 4},
    {key: 'E', time: 4},
    {key: 'E', time: 4},

    {key: '0', time: 4},
    {key: '0', time: 4},
    {key: '0', time: 4},
    {key: 'E', time: 4},

    {key: 'Y', time: 4},
    {key: '0', time: 4},
    {key: 'T', time: 4},
    {key: '0', time: 4},

    {key: 'E', time: 4},
    {key: 'W', time: 2},
    {key: 'Q', time: 2},
    {key: '0', time: 4},
    {key: '0', time: 4},


],
    [
        {key: '0', time: 4},
        {key: '0', time: 4},
        {key: '0', time: 4},
        {key: '0', time: 4},

        {key: 'N', time: 4},
        {key: 'A', time: 4},
        {key: 'D', time: 4},
        {key: 'A', time: 4},

        {key: 'C', time: 4},
        {key: 'V', time: 4},
        {key: 'M', time: 4},
        {key: '0', time: 4},

        {key: 'V', time: 4},
        {key: 'N', time: 4},
        {key: 'A', time: 4},
        {key: 'N', time: 4},

        {key: 'Z', time: 4},
        {key: 'B', time: 4},
        {key: 'A', time: 4},
        {key: '0', time: 4},

        {key: 'X', time: 4},
        {key: 'V', time: 4},
        {key: 'N', time: 4},
        {key: 'V', time: 4},

        {key: 'N', time: 4},
        {key: 'C', time: 4},
        {key: 'N', time: 4},
        {key: '0', time: 4},

        {key: 'M', time: 4},
        {key: 'V', time: 4},
        {key: 'M', time: 4},
        {key: 'V', time: 4},

        {key: 'C', time: 4},
        {key: 'M', time: 4},
        {key: 'C', time: 4},
        {key: '0', time: 4},

        {key: 'N', time: 4},
        {key: 'C', time: 4},
        {key: 'N', time: 4},
        {key: 'C', time: 4},

        {key: 'C', time: 4},
        {key: 'M', time: 4},
        {key: 'C', time: 4},
        {key: '0', time: 4},

        {key: 'V', time: 4},
        {key: 'Z', time: 4},
        {key: 'V', time: 4},
        {key: 'Z', time: 4},

        {key: 'Z', time: 4},
        {key: 'B', time: 4},
        {key: 'A', time: 4},
        {key: '0', time: 4},

        {key: 'X', time: 4},
        {key: 'N', time: 4},
        {key: 'X', time: 4},
        {key: 'N', time: 4},

        {key: 'N', time: 4},
        {key: 'C', time: 4},
        {key: 'N', time: 4},
        {key: 'C', time: 4},

        {key: 'V', time: 4},
        {key: 'A', time: 4},
        {key: 'C', time: 4},
        {key: 'M', time: 4},

        {key: 'N', time: 4},
        {key: 'C', time: 4},
        {key: 'N', time: 4},
        {key: '0', time: 4},

        {key: 'Z', time: 4},
        {key: 'B', time: 4},
        {key: 'A', time: 4},
        {key: 'B', time: 4},

        {key: 'B', time: 4},
        {key: 'X', time: 4},
        {key: 'M', time: 4},
        {key: '0', time: 4},

        {key: 'N', time: 4},
        {key: 'C', time: 4},
        {key: 'N', time: 4},
        {key: 'C', time: 4},

        {key: 'C', time: 4},
        {key: 'M', time: 4},
        {key: 'C', time: 4},
        {key: '0', time: 4},

        {key: 'V', time: 4},
        {key: 'Z', time: 4},
        {key: 'V', time: 4},
        {key: 'Z', time: 4},

        {key: 'C', time: 4},
        {key: 'Z', time: 4},
        {key: 'B', time: 4},
        {key: 'Z', time: 4},

        {key: 'X', time: 4},
        {key: 'N', time: 4},
        {key: 'X', time: 4},
        {key: 'N', time: 4},

        {key: 'C', time: 4},
        {key: 'M', time: 4},
        {key: 'C', time: 4},
        {key: 'M', time: 4},

        {key: 'C', time: 4},
        {key: 'C', time: 4},
        {key: 'C', time: 4},
        {key: 'C', time: 4},

        {key: 'N', time: 4},
        {key: 'C', time: 4},
        {key: 'V', time: 4},
        {key: 'X', time: 4},

        {key: 'V', time: 4},
        {key: 'Z', time: 4},
        {key: 'V', time: 4},
        {key: 'Z', time: 4}
    ]
]
flowDance = [
    [
        {key: 'E', time: 2},
        {key: 'W', time: 2},
        {key: 'Y', time: 2},
        {key: 'W', time: 2},
        {key: 'E', time: 2},
        {key: 'W', time: 2},
        {key: 'H', time: 2},
        {key: 'W', time: 2},

        {key: 'E', time: 2},
        {key: 'W', time: 2},
        {key: 'Y', time: 2},
        {key: 'W', time: 2},
        {key: 'E', time: 2},
        {key: 'W', time: 2},
        {key: 'H', time: 2},
        {key: 'W', time: 2},

        {key: 'E', time: 2},
        {key: 'W', time: 2},
        {key: 'Y', time: 2},
        {key: 'W', time: 2},
        {key: 'E', time: 2},
        {key: 'W', time: 2},
        {key: 'H', time: 2},
        {key: 'W', time: 2},

        {key: 'E', time: 2},
        {key: 'W', time: 2},
        {key: 'Y', time: 2},
        {key: 'W', time: 2},
        {key: 'E', time: 2},
        {key: 'W', time: 2},
        {key: 'H', time: 2},
        {key: 'W', time: 2},

        {key: 'E', time: 2},
        {key: 'W', time: 2},
        {key: 'Y', time: 2},
        {key: 'W', time: 2},
        {key: 'E', time: 2},
        {key: 'W', time: 2},
        {key: 'H', time: 2},
        {key: 'W', time: 2},

        {key: 'E', time: 2},
        {key: 'W', time: 2},
        {key: 'Y', time: 2},
        {key: 'W', time: 2},
        {key: 'E', time: 2},
        {key: 'W', time: 2},
        {key: 'H', time: 2},
        {key: 'W', time: 2},

        {key: 'E', time: 2},
        {key: 'W', time: 2},
        {key: 'Y', time: 2},
        {key: 'W', time: 2},
        {key: 'E', time: 2},
        {key: 'W', time: 2},
        {key: 'H', time: 2},
        {key: 'W', time: 2},


        {key: 'E', time: 4},
        {key: 'E', time: 4},
        {key: 'E', time: 4},
        {key: 'E', time: 4},
        // 9
        {key: 'E', time: 4},
        {key: 'E', time: 1},
        {key: 'H', time: 1},
        {key: 'Q', time: 1},
        {key: 'E', time: 1},
        {key: 'G', time: 4},
        {key: 'J', time: 0},
        {key: 'W', time: 0},
        {key: 'J', time: 1},
        {key: 'W', time: 1},
        {key: 'T', time: 2},

        {key: 'J', time: 3},
        {key: 'U', time: 1},
        {key: 'Y', time: 3},
        {key: 'T', time: 1},
        {key: 'E', time: 4},
        {key: 'sE', time: 4},

        {key: 'E', time: 4},
        {key: 'Y', time: 4},
        {key: 'sW', time: 2},
        {key: 'sW', time: 1},
        {key: 'sE', time: 1},
        {key: 'sW', time: 1},
        {key: '0', time: 1},
        {key: 'U', time: 2},
        {key: 'T', time: 2},

        {key: 'Y', time: 4},
        {key: '0', time: 4},
        {key: '0', time: 4},
        {key: '0', time: 2},
        {key: 'E', time: 2},

        // 13

        {key: 'H', time: 1},
        {key: 'Q', time: 1},
        {key: 'E', time: 2},
        {key: 'H', time: 1},
        {key: 'Q', time: 0},
        {key: 'E', time: 0},
        {key: 'H', time: 1},
        {key: 'Q', time: 1},
        {key: 'E', time: 1},
        {key: 'G', time: 4},
        {key: 'J', time: 0},
        {key: 'W', time: 0},
        {key: 'J', time: 4},
        {key: 'W', time: 0},
        {key: 'T', time: 0},

        {key: 'J', time: 2},
        {key: 'W', time: 0},
        {key: 'J', time: 2},
        {key: 'T', time: 0},
        {key: 'Y', time: 2},
        {key: 'U', time: 2},
        {key: 'E', time: 1},
        {key: 'sQ', time: 1},
        {key: 'W', time: 1},
        {key: 'U', time: 1},
        {key: 'Q', time: 1},
        {key: 'Y', time: 1},
        {key: 'U', time: 1},
        {key: 'T', time: 1},

        {key: 'Y', time: 1},
        {key: 'sE', time: 1},
        {key: 'sW', time: 1},
        {key: 'sE', time: 1},
        {key: 'Y', time: 1},
        {key: 'sE', time: 1},
        {key: 'sW', time: 1},
        {key: 'sE', time: 1},
        {key: 'Y', time: 1},
        {key: 'sE', time: 1},
        {key: 'sW', time: 1},
        {key: 'sE', time: 1},
        {key: 'Y', time: 1},
        {key: 'sE', time: 1},
        {key: 'sW', time: 1},
        {key: 'sE', time: 1},

        {key: 'Y', time: 1},
        {key: 'sE', time: 1},
        {key: 'sQ', time: 1},
        {key: 'sE', time: 1},
        {key: 'Y', time: 1},
        {key: 'sE', time: 1},
        {key: 'sQ', time: 1},
        {key: 'sE', time: 1},
        {key: 'Y', time: 1},
        {key: 'sE', time: 1},
        {key: 'sQ', time: 1},
        {key: 'sE', time: 1},
        {key: 'Y', time: 1},
        {key: 'sE', time: 1},
        {key: 'sQ', time: 1},
        {key: 'sE', time: 1},

        {key: 'sq', time: 1},
        {key: 'e', time: 1},
        {key: 'u', time: 1},
        {key: 'e', time: 1},
        {key: 'se', time: 1},
        {key: 'e', time: 1},
        {key: 'sw', time: 1},
        {key: 'e', time: 1},
        {key: 'u', time: 1},
        {key: 'j', time: 1},
        {key: 'y', time: 1},
        {key: 'j', time: 1},
        {key: 't', time: 2},
        {key: 'e', time: 1},
        {key: 't', time: 1},

        {key: 'y', time: 1},
        {key: 'q', time: 1},
        {key: 't', time: 1},
        {key: 'q', time: 1},
        {key: 'y', time: 1},
        {key: 'q', time: 1},
        {key: 'sq', time: 1},
        {key: 'q', time: 1},
        {key: 't', time: 1},
        {key: 'q', time: 1},
        {key: 'r', time: 1},
        {key: 'q', time: 1},
        {key: 'e', time: 2},
        {key: 'e', time: 1},
        {key: 't', time: 1},

        {key: 'r', time: 1},
        {key: 'h', time: 1},
        {key: 'e', time: 1},
        {key: 'h', time: 1},
        {key: 'w', time: 1},
        {key: 'h', time: 1},
        {key: 'r', time: 1},
        {key: 'h', time: 1},
        {key: 'e', time: 1},
        {key: 'd', time: 1},
        {key: 'w', time: 1},
        {key: 'd', time: 1},
        {key: 'q', time: 1},
        {key: 'd', time: 1},
        {key: 'e', time: 1},
        {key: 'd', time: 1},

        {key: 'w', time: 1},
        {key: 'f', time: 1},
        {key: 'q', time: 1},
        {key: 'f', time: 1},
        {key: 'j', time: 1},
        {key: 'f', time: 1},
        {key: 'h', time: 1},
        {key: 'f', time: 1},
        {key: 'f', time: 2},
        {key: 'f', time: 2},
        {key: 'd', time: 4},

        {key: 'q', time: 1},
        {key: 'd', time: 1},
        {key: 'j', time: 1},
        {key: 'd', time: 1},
        {key: 'q', time: 1},
        {key: 'd', time: 1},
        {key: 'w', time: 1},
        {key: 'd', time: 1},
        {key: 'j', time: 1},
        {key: 'd', time: 1},
        {key: 'h', time: 1},
        {key: 'd', time: 1},
        {key: 'g', time: 2},
        {key: 'd', time: 1},
        {key: 'g', time: 1},

        {key: 'h', time: 1},
        {key: 'a', time: 1},
        {key: 'g', time: 1},
        {key: 'a', time: 1},
        {key: 'h', time: 1},
        {key: 'a', time: 1},
        {key: 'q', time: 1},
        {key: 'a', time: 1},
        {key: 'g', time: 1},
        {key: 'a', time: 1},
        {key: 'f', time: 1},
        {key: 'a', time: 1},
        {key: 'g', time: 2},
        {key: 'd', time: 1},
        {key: 'g', time: 1},

        {key: 'f', time: 2},
        {key: 'r', time: 1},
        {key: 'e', time: 1},
        {key: 'w', time: 1},
        {key: 'q', time: 1},
        {key: 'j', time: 2},
        {key: 'e', time: 1},
        {key: 'w', time: 1},
        {key: 'e', time: 1},
        {key: 'r', time: 1},
        {key: 'e', time: 1},
        {key: 'w', time: 1},
        {key: 'q', time: 1},
        {key: 'j', time: 1},

        {key: 'h', time: 2},
        {key: 'e', time: 2},
        {key: 'g', time: 2},
        {key: 'e', time: 2},
        {key: 'h', time: 4},
        {key: 'h', time: 4},

        {key: 'h', time: 4},
        {key: 'h', time: 1},
        {key: 'h', time: 1},
        {key: 'q', time: 1},
        {key: 'e', time: 1},
        {key: 'g', time: 4},
        {key: 'j', time: 4},

        {key: 'j', time: 4},
        {key: 'u', time: 1},
        {key: 'y', time: 4},
        {key: 't', time: 1},
        {key: 'e', time: 4},
        {key: 'se', time: 4},

        {key: 'r', time: 4},
        {key: 'y', time: 4},
        {key: 'sw', time: 2},
        {key: 'sw', time: 1},
        {key: 'se', time: 1},
        {key: 'sw', time: 0},
        {key: 'u', time: 2},
        {key: 't', time: 2},

        {key: 'y', time: 4},
        {key: 'y', time: 4},
        {key: 'y', time: 4},
        {key: '0', time: 2},
        {key: 'e', time: 2},

        {key: 'h', time: 4},
        {key: 'h', time: 1},
        {key: 'h', time: 1},
        {key: 'q', time: 1},
        {key: 'e', time: 1},
        {key: 't', time: 4},
        {key: 'j', time: 4},

        {key: 'j', time: 2},
        {key: 'j', time: 2},
        {key: 'y', time: 2},
        {key: 'u', time: 2},
        {key: 'sq', time: 1},
        {key: 'e', time: 1},
        {key: 'u', time: 1},
        {key: 'w', time: 1},
        {key: 'y', time: 1},
        {key: 'q', time: 1},
        {key: 't', time: 1},
        {key: 'j', time: 1},

        {key: 'y', time: 1},
        {key: 'se', time: 1},
        {key: 'sw', time: 1},
        {key: 'se', time: 1},
        {key: 'y', time: 1},
        {key: 'se', time: 1},
        {key: 'sw', time: 1},
        {key: 'se', time: 1},
        {key: 'y', time: 1},
        {key: 'se', time: 1},
        {key: 'sw', time: 1},
        {key: 'se', time: 1},
        {key: 'y', time: 1},
        {key: 'se', time: 1},
        {key: 'sw', time: 1},
        {key: 'se', time: 1},

        {key: 'y', time: 1},
        {key: 'se', time: 1},
        {key: 'sq', time: 1},
        {key: 'se', time: 1},
        {key: 'y', time: 1},
        {key: 'se', time: 1},
        {key: 'sq', time: 1},
        {key: 'se', time: 1},
        {key: 'y', time: 1},
        {key: 'se', time: 1},
        {key: 'sq', time: 1},
        {key: 'se', time: 1},
        {key: 'y', time: 1},
        {key: 'se', time: 1},
        {key: 'sq', time: 1},
        {key: 'se', time: 1},

        {key: 'h', time: 4},
        {key: 'h', time: 1},
        {key: 'h', time: 1},
        {key: 'q', time: 1},
        {key: 'e', time: 1},
        {key: 'g', time: 4},
        {key: 'j', time: 4},

        {key: 'j', time: 4},
        {key: 'u', time: 1},
        {key: 'y', time: 2},
        {key: 't', time: 1},
        {key: 'e', time: 4},
        {key: 'se', time: 4},

        {key: 'r', time: 4},
        {key: 'y', time: 4},
        {key: 'sw', time: 2},
        {key: 'sw', time: 1},
        {key: 'se', time: 1},
        {key: 'sw', time: 0},
        {key: 'u', time: 2},
        {key: 't', time: 2},

    ],
    [
        {key: 'V', time: 2},
        {key: 'A', time: 2},
        {key: 'V', time: 2},
        {key: 'B', time: 2},
        {key: 'N', time: 4},
        {key: '0', time: 4},

        {key: 'B', time: 2},
        {key: 'S', time: 2},
        {key: 'B', time: 2},
        {key: 'N', time: 2},
        {key: 'J', time: 4},
        {key: '0', time: 4},

        {key: 'N', time: 2},
        {key: 'D', time: 2},
        {key: 'H', time: 2},
        {key: 'J', time: 2},
        {key: 'Q', time: 4},
        {key: '0', time: 4},

        {key: '0', time: 4},
        {key: '0', time: 4},
        {key: '0', time: 4},
        {key: '0', time: 4},

        {key: 'V', time: 2},
        {key: 'A', time: 2},
        {key: 'V', time: 2},
        {key: 'B', time: 2},
        {key: 'N', time: 4},
        {key: '0', time: 4},

        {key: 'B', time: 2},
        {key: 'S', time: 2},
        {key: 'B', time: 2},
        {key: 'N', time: 2},
        {key: 'J', time: 4},
        {key: '0', time: 4},

        {key: 'N', time: 2},
        {key: 'D', time: 2},
        {key: 'H', time: 2},
        {key: 'J', time: 2},
        {key: 'Q', time: 4},
        {key: '0', time: 4},

        {key: 'N', time: 4},
        {key: 'N', time: 4},
        {key: 'N', time: 4},
        {key: 'N', time: 4},

        {key: '0', time: 2},
        {key: 'A', time: 4},
        {key: '0', time: 2},
        {key: 'B', time: 2},
        {key: 'S', time: 2},
        {key: 'G', time: 4},

        {key: 'C', time: 2},
        {key: 'M', time: 2},
        {key: 'D', time: 2},
        {key: 'G', time: 2},
        {key: 'N', time: 2},
        {key: 'D', time: 2},
        {key: 'H', time: 2},
        {key: 'D', time: 2},

        {key: 'V', time: 2},
        {key: 'A', time: 2},
        {key: 'F', time: 2},
        {key: 'A', time: 2},
        {key: 'B', time: 2},
        {key: 'S', time: 2},
        {key: 'G', time: 2},
        {key: 'S', time: 2},

        {key: 'N', time: 2},
        {key: 'D', time: 2},
        {key: 'H', time: 2},
        {key: 'J', time: 2},
        {key: 'Q', time: 2},
        {key: 'D', time: 2},
        {key: 'H', time: 4},

        {key: 'V', time: 2},
        {key: 'A', time: 4},
        {key: '0', time: 2},
        {key: 'B', time: 2},
        {key: 'S', time: 2},
        {key: 'G', time: 4},

        {key: 'C', time: 2},
        {key: 'M', time: 2},
        {key: 'D', time: 4},
        {key: 'N', time: 2},
        {key: 'D', time: 2},
        {key: 'H', time: 4},

        {key: 'V', time: 2},
        {key: 'A', time: 2},
        {key: 'F', time: 4},
        {key: 'B', time: 2},
        {key: 'S', time: 2},
        {key: 'G', time: 4},

        {key: 'N', time: 2},
        {key: 'D', time: 2},
        {key: 'H', time: 2},
        {key: 'J', time: 2},
        {key: 'Q', time: 4},
        {key: '0', time: 4},
        {key: 'an', time: 1},
        {key: 'c', time: 1},
        {key: 'n', time: 1},
        {key: 'm', time: 1},
        {key: 'a', time: 2},
        {key: 'd', time: 2},
        {key: 'c', time: 2},
        {key: 'm', time: 2},
        {key: 'd', time: 4},

        {key: 'av', time: 1},
        {key: 'z', time: 1},
        {key: 'v', time: 1},
        {key: 'b', time: 1},
        {key: 'n', time: 2},
        {key: 'a', time: 2},
        {key: 'z', time: 2},
        {key: 'b', time: 2},
        {key: 'a', time: 4},

        {key: 'ax', time: 2},
        {key: 'n', time: 2},
        {key: 'f', time: 1},
        {key: 'd', time: 1},
        {key: 's', time: 1},
        {key: 'a', time: 1},
        {key: 'an', time: 2},
        {key: 'ac', time: 2},
        {key: 'c', time: 1},
        {key: 'x', time: 1},
        {key: 'z', time: 1},
        {key: 'am', time: 1},

        {key: 'am', time: 2},
        {key: 'v', time: 2},
        {key: 'm', time: 2},
        {key: 'v', time: 2},
        {key: 'x', time: 2},
        {key: 'z', time: 2},
        {key: 'am', time: 2},
        {key: 'ac', time: 2},
        //21
        {key: 'an', time: 1},
        {key: 'c', time: 1},
        {key: 'n', time: 1},
        {key: 'm', time: 1},
        {key: 'a', time: 1},
        {key: 'm', time: 1},
        {key: 'n', time: 1},
        {key: 'c', time: 1},
        {key: 'ac', time: 2},
        {key: 'am', time: 2},
        {key: 'b', time: 2},
        {key: 'am', time: 2},

        {key: 'av', time: 1},
        {key: 'z', time: 1},
        {key: 'v', time: 1},
        {key: 'b', time: 1},
        {key: 'n', time: 1},
        {key: 'b', time: 1},
        {key: 'v', time: 1},
        {key: 'z', time: 1},
        {key: 'az', time: 2},
        {key: 'ab', time: 2},
        {key: 'c', time: 2},
        {key: 'ab', time: 2},

        {key: 'ax', time: 1},
        {key: 'an', time: 1},
        {key: 'x', time: 1},
        {key: 'c', time: 1},
        {key: 'v', time: 1},
        {key: 'c', time: 1},
        {key: 'x', time: 1},
        {key: 'an', time: 1},
        {key: 'an', time: 1},
        {key: 'ac', time: 1},
        {key: 'an', time: 1},
        {key: 'am', time: 1},
        {key: 'az', time: 1},
        {key: 'ax', time: 1},
        {key: 'ac', time: 2},

        {key: 'ax', time: 4},
        {key: 'am', time: 4},
        {key: 'an', time: 0},
        {key: 'an', time: 2},
        {key: 'c', time: 2},
        {key: 'n', time: 4},
        //25
        {key: 'av', time: 2},
        {key: 'v', time: 2},
        {key: 'a', time: 2},
        {key: 'v', time: 2},
        {key: 'ab', time: 2},
        {key: 'b', time: 2},
        {key: 's', time: 2},
        {key: 'b', time: 2},

        {key: 'ac', time: 2},
        {key: 'c', time: 2},
        {key: 'b', time: 2},
        {key: 'c', time: 2},
        {key: 'an', time: 2},
        {key: 'c', time: 2},
        {key: 'a', time: 2},
        {key: 'c', time: 2},

        {key: 'av', time: 2},
        {key: 'v', time: 2},
        {key: 'a', time: 2},
        {key: 'v', time: 2},
        {key: 'ab', time: 2},
        {key: 'b', time: 2},
        {key: 's', time: 2},
        {key: 'b', time: 2},

        {key: 'an', time: 2},
        {key: 'd', time: 2},
        {key: 'h', time: 2},
        {key: 'j', time: 2},
        {key: 'h', time: 2},
        {key: 'd', time: 2},
        {key: 'h', time: 4},
        //29
        {key: 'aM', time: 2},
        {key: 'v', time: 2},
        {key: 'a', time: 2},
        {key: 'v', time: 2},
        {key: 'ab', time: 2},
        {key: 'b', time: 2},
        {key: 's', time: 2},
        {key: 'b', time: 2},

        {key: 'ac', time: 2},
        {key: 'c', time: 2},
        {key: 'b', time: 2},
        {key: 'c', time: 2},
        {key: 'an', time: 2},
        {key: 'c', time: 2},
        {key: 'a', time: 2},
        {key: 'c', time: 2},

        {key: 'av', time: 2},
        {key: 'z', time: 2},
        {key: 'v', time: 4},
        {key: 'ab', time: 2},
        {key: 'x', time: 2},
        {key: 'g', time: 4},

        {key: 'an', time: 2},
        {key: 'c', time: 2},
        {key: 'n', time: 2},
        {key: 'm', time: 2},
        {key: 'a', time: 6},
        {key: 'n', time: 2},
        //33
        {key: 'am', time: 2},
        {key: 'v', time: 2},
        {key: 'a', time: 2},
        {key: 'v', time: 2},
        {key: 'ab', time: 2},
        {key: 'm', time: 1},
        {key: 's', time: 1},
        {key: 'g', time: 2},
        {key: 's', time: 2},

        {key: 'ac', time: 2},
        {key: 'c', time: 2},
        {key: 'b', time: 2},
        {key: 'c', time: 2},
        {key: 'an', time: 1},
        {key: 'c', time: 1},
        {key: 'n', time: 1},
        {key: 'a', time: 1},
        {key: 'd', time: 2},
        {key: 'h', time: 2},

        {key: 'av', time: 1},
        {key: 'z', time: 1},
        {key: 'v', time: 1},
        {key: 'n', time: 1},
        {key: 'a', time: 2},
        {key: 'f', time: 2},
        {key: 'ab', time: 2},
        {key: 'b', time: 2},
        {key: 's', time: 2},
        {key: 'b', time: 2},



    ]
]

lemon =[[
    {key: '0', time: 4},
    {key: '0', time: 4},
    {key: '0', time: 4},
    {key: '0', time: 2},
    {key: 'Q', time: 1},
    {key: 'W', time: 1},

    {key: 'E', time: 2},
    {key: 'Q', time: 1},
    {key: 'H', time: 3},
    {key: 'W', time: 2},
    {key: 'J', time: 2},
    {key: 'G', time: 1},
    {key: 'D', time: 3},
    {key: 'J', time: 2},

    {key: 'H', time: 2},
    {key: 'G', time: 1},
    {key: 'A', time: 3},
    {key: 'G', time: 2},
    {key: 'D', time: 6},
    {key: 'S', time: 1},
    {key: 'D', time: 1},

    {key: 'N', time: 4},
    {key: 'F', time: 2},
    {key: 'J', time: 1},
    {key: 'Q', time: 1},
    {key: 'A', time: 4},
    {key: 'F', time: 2},
    {key: 'D', time: 1},
    {key: 'F', time: 1},

    {key: 'F', time: 4},
    {key: 'Q', time: 2},
    {key: 'J', time: 1},
    {key: 'H', time: 1},
    {key: 'D', time: 4},
    {key: '0', time: 2},
    {key: 'Q', time: 1},
    {key: 'W', time: 1},

    {key: 'E', time: 2},
    {key: 'Q', time: 1},
    {key: 'H', time: 3},
    {key: 'W', time: 2},
    {key: 'J', time: 2},
    {key: 'G', time: 1},
    {key: 'D', time: 3},
    {key: 'J', time: 2},

    {key: 'H', time: 2},
    {key: 'G', time: 1},
    {key: 'A', time: 3},
    {key: 'G', time: 2},
    {key: 'D', time: 6},
    {key: 'S', time: 1},
    {key: 'D', time: 1},

    {key: 'N', time: 4},
    {key: 'G', time: 2},
    {key: 'F', time: 1},
    {key: 'G', time: 1},
    {key: 'D', time: 2},
    {key: 'G', time: 2},
    {key: 'D', time: 2},
    {key: 'E', time: 2},

    {key: 'G', time: 2},
    {key: 'W', time: 1},
    {key: 'J', time: 2},
    {key: 'Q', time: 1},
    {key: 'Q', time: 8},





],
    [
    {key: '0', time: 4},
    {key: '0', time: 4},
    {key: '0', time: 4},
    {key: '0', time: 4},

    {key: 'N', time: 8},
    {key: 'B', time: 8},

    {key: 'V', time: 8},
    {key: 'Z', time: 8},

    {key: 'V', time: 8},
    {key: 'Z', time: 8},

    {key: 'Z', time: 8},
    {key: 'C', time: 2},
    {key: 'M', time: 2},
    {key: 'D', time: 4},


    {key: 'N', time: 2},
    {key: 'C', time: 2},
    {key: 'A', time: 4},
    {key: 'B', time: 2},
    {key: 'X', time: 2},
    {key: 'M', time: 4},

    {key: 'V', time: 2},
    {key: 'Z', time: 2},
    {key: 'N', time: 4},
    {key: 'Z', time: 2},
    {key: 'B', time: 2},
    {key: 'A', time: 4},

    {key: 'V', time: 2},
    {key: 'Z', time: 2},
    {key: 'N', time: 4},
    {key: 'Z', time: 2},
    {key: 'B', time: 2},
    {key: 'A', time: 4},

    {key: 'G', time: 2},
    {key: 'S', time: 2},
    {key: 'F', time: 4},
    {key: 'Z', time: 8},


    {key: '0', time: 4},
    {key: '0', time: 4},
    {key: '0', time: 4},
    {key: '0', time: 4},
    {key: '0', time: 4},
    {key: '0', time: 4},
    {key: '0', time: 4},
    {key: '0', time: 4},
    {key: '0', time: 4},
    {key: '0', time: 4},
    {key: '0', time: 4},
    {key: '0', time: 4},
    {key: '0', time: 4},
    {key: '0', time: 4},

]]
