art_sky = [[
    {key: '0', time: 4},
    {key: '0', time: 4},
    {key: 'H', time: 4},
    {key: 'J', time: 4},

    {key: 'Q', time: 6},
    {key: 'J', time: 2},
    {key: 'Q', time: 4},
    {key: 'E', time: 4},

    {key: 'J', time: 4},
    {key: '0', time: 4},
    {key: '0', time: 4},
    {key: 'D', time: 4},
    {key: 'H', time: 6},
    {key: 'G', time: 2},
    {key: 'H', time: 4},
    {key: 'Q', time: 4},
    {key: 'G', time: 4},

    {key: '0', time: 4},
    {key: '0', time: 4},

    {key: 'F', time: 2},
    {key: 'D', time: 2},
    {key: 'F', time: 6},
    {key: 'D', time: 2},
    {key: 'F', time: 4},
    {key: 'Q', time: 4},
    {key: 'D', time: 4},

    {key: '0', time: 6},
    {key: 'Q', time: 2},
    {key: 'Q', time: 2},
    {key: 'Q', time: 2},
    {key: 'J', time: 4},
     {key: '0', time: 2},

     {key: 'F', time: 2},
    {key: 'F', time: 4},
    {key: 'J', time: 4},
    //
    {key: 'H', time: 4},
    {key: '0', time: 4},
    {key: '0', time: 4},
    {key: 'H', time: 2},
    {key: 'J', time: 2},

    {key: 'Q', time: 6},
    {key: 'J', time: 2},
    {key: 'Q', time: 4},
    {key: 'E', time: 4},

    {key: 'J', time: 4},
    {key: '0', time: 4},
    {key: '0', time: 4},
    {key: 'D', time: 2},
    {key: 'D', time: 2},

    {key: 'H', time: 6},
    {key: 'G', time: 2},
    {key: 'H', time: 4},
    {key: 'Q', time: 4},

    {key: 'G', time: 4},
    {key: '0', time: 4},
    {key: '0', time: 4},
    {key: 'D', time: 4},

    {key: 'F', time: 4},
    {key: 'Q', time: 2},
    {key: 'J', time: 2},
    {key: '0', time: 4},
    {key: 'Q', time: 4},

    {key: 'W', time: 4},
    {key: 'E', time: 2},
    {key: 'Q', time: 2},
    {key: '0', time: 4},
    {key: '0', time: 4},

    {key: 'Q', time: 2},
    {key: 'J', time: 2},
    {key: 'H', time: 4},
    {key: 'J', time: 4},
    {key: 'G', time: 4},

    {key: 'H', time: 4},
    {key: '0', time: 4},
    {key: '0', time: 4},
    {key: 'Q', time: 2},
    {key: 'W', time: 2},

    {key: 'E', time: 6},
    {key: 'W', time: 2},
    {key: 'E', time: 4},
    {key: 'T', time: 4},

    {key: 'W', time: 4},
    {key: '0', time: 4},
    {key: '0', time: 4},
    {key: 'G', time: 2},
    {key: 'G', time: 2},

    {key: 'Q', time: 6},
    {key: 'J', time: 2},
    {key: 'Q', time: 4},
    {key: 'E', time: 4},

    {key: 'E', time: 4},
    {key: 'E', time: 4},
    {key: 'E', time: 4},
    {key: 'E', time: 4},

    {key: 'H', time: 2},
    {key: 'J', time: 2},
    {key: 'Q', time: 4},
    {key: 'J', time: 2},
    {key: 'Q', time: 2},
    {key: 'W', time: 4},

    {key: 'Q', time: 6},
    {key: 'G', time: 2},
    {key: 'G', time: 4},
    {key: '0', time: 4},

    {key: 'R', time: 4},
    {key: 'E', time: 4},
    {key: 'W', time: 4},
    {key: 'Q', time: 4},

    {key: 'E', time: 4},
    {key: 'E', time: 4},
    {key: 'E', time: 4},
    {key: 'E', time: 4},

    {key: '0', time: 4},
    {key: '0', time: 4},
    {key: '0', time: 4},
    {key: 'E', time: 4},

    {key: 'Y', time: 4},
    {key: '0', time: 4},
    {key: 'T', time: 4},
    {key: '0', time: 4},

    {key: 'E', time: 4},
    {key: 'W', time: 2},
    {key: 'Q', time: 2},
    {key: '0', time: 4},
    {key: '0', time: 4},


],
    [
        {key: '0', time: 4},
        {key: '0', time: 4},
        {key: '0', time: 4},
        {key: '0', time: 4},

        {key: 'N', time: 4},
        {key: 'A', time: 4},
        {key: 'D', time: 4},
        {key: 'A', time: 4},

        {key: 'C', time: 4},
        {key: 'V', time: 4},
        {key: 'M', time: 4},
        {key: '0', time: 4},

        {key: 'V', time: 4},
        {key: 'N', time: 4},
        {key: 'A', time: 4},
        {key: 'N', time: 4},

        {key: 'Z', time: 4},
        {key: 'B', time: 4},
        {key: 'A', time: 4},
        {key: '0', time: 4},

        {key: 'X', time: 4},
        {key: 'V', time: 4},
        {key: 'N', time: 4},
        {key: 'V', time: 4},

        {key: 'N', time: 4},
        {key: 'C', time: 4},
        {key: 'N', time: 4},
        {key: '0', time: 4},

        {key: 'M', time: 4},
        {key: 'V', time: 4},
        {key: 'M', time: 4},
        {key: 'V', time: 4},

        {key: 'C', time: 4},
        {key: 'M', time: 4},
        {key: 'C', time: 4},
        {key: '0', time: 4},

        {key: 'N', time: 4},
        {key: 'C', time: 4},
        {key: 'N', time: 4},
        {key: 'C', time: 4},

        {key: 'C', time: 4},
        {key: 'M', time: 4},
        {key: 'C', time: 4},
        {key: '0', time: 4},

        {key: 'V', time: 4},
        {key: 'Z', time: 4},
        {key: 'V', time: 4},
        {key: 'Z', time: 4},

        {key: 'Z', time: 4},
        {key: 'B', time: 4},
        {key: 'A', time: 4},
        {key: '0', time: 4},

        {key: 'X', time: 4},
        {key: 'N', time: 4},
        {key: 'X', time: 4},
        {key: 'N', time: 4},

        {key: 'N', time: 4},
        {key: 'C', time: 4},
        {key: 'N', time: 4},
        {key: 'C', time: 4},

        {key: 'V', time: 4},
        {key: 'A', time: 4},
        {key: 'C', time: 4},
        {key: 'M', time: 4},

        {key: 'N', time: 4},
        {key: 'C', time: 4},
        {key: 'N', time: 4},
        {key: '0', time: 4},

        {key: 'Z', time: 4},
        {key: 'B', time: 4},
        {key: 'A', time: 4},
        {key: 'B', time: 4},

        {key: 'B', time: 4},
        {key: 'X', time: 4},
        {key: 'M', time: 4},
        {key: '0', time: 4},

        {key: 'N', time: 4},
        {key: 'C', time: 4},
        {key: 'N', time: 4},
        {key: 'C', time: 4},

        {key: 'C', time: 4},
        {key: 'M', time: 4},
        {key: 'C', time: 4},
        {key: '0', time: 4},

        {key: 'V', time: 4},
        {key: 'Z', time: 4},
        {key: 'V', time: 4},
        {key: 'Z', time: 4},

        {key: 'C', time: 4},
        {key: 'Z', time: 4},
        {key: 'B', time: 4},
        {key: 'Z', time: 4},

        {key: 'X', time: 4},
        {key: 'N', time: 4},
        {key: 'X', time: 4},
        {key: 'N', time: 4},

        {key: 'C', time: 4},
        {key: 'M', time: 4},
        {key: 'C', time: 4},
        {key: 'M', time: 4},

        {key: 'C', time: 4},
        {key: 'C', time: 4},
        {key: 'C', time: 4},
        {key: 'C', time: 4},

        {key: 'N', time: 4},
        {key: 'C', time: 4},
        {key: 'V', time: 4},
        {key: 'X', time: 4},

        {key: 'V', time: 4},
        {key: 'Z', time: 4},
        {key: 'V', time: 4},
        {key: 'Z', time: 4}
    ]
]
flowDance = [
    [
        {key: 'E', time: 2},
        {key: 'W', time: 2},
        {key: 'Y', time: 2},
        {key: 'W', time: 2},
        {key: 'E', time: 2},
        {key: 'W', time: 2},
        {key: 'H', time: 2},
        {key: 'W', time: 2},

        {key: 'E', time: 2},
        {key: 'W', time: 2},
        {key: 'Y', time: 2},
        {key: 'W', time: 2},
        {key: 'E', time: 2},
        {key: 'W', time: 2},
        {key: 'H', time: 2},
        {key: 'W', time: 2},

        {key: 'E', time: 2},
        {key: 'W', time: 2},
        {key: 'Y', time: 2},
        {key: 'W', time: 2},
        {key: 'E', time: 2},
        {key: 'W', time: 2},
        {key: 'H', time: 2},
        {key: 'W', time: 2},

        {key: 'E', time: 2},
        {key: 'W', time: 2},
        {key: 'Y', time: 2},
        {key: 'W', time: 2},
        {key: 'E', time: 2},
        {key: 'W', time: 2},
        {key: 'H', time: 2},
        {key: 'W', time: 2},

        {key: 'E', time: 2},
        {key: 'W', time: 2},
        {key: 'Y', time: 2},
        {key: 'W', time: 2},
        {key: 'E', time: 2},
        {key: 'W', time: 2},
        {key: 'H', time: 2},
        {key: 'W', time: 2},

        {key: 'E', time: 2},
        {key: 'W', time: 2},
        {key: 'Y', time: 2},
        {key: 'W', time: 2},
        {key: 'E', time: 2},
        {key: 'W', time: 2},
        {key: 'H', time: 2},
        {key: 'W', time: 2},

        {key: 'E', time: 2},
        {key: 'W', time: 2},
        {key: 'Y', time: 2},
        {key: 'W', time: 2},
        {key: 'E', time: 2},
        {key: 'W', time: 2},
        {key: 'H', time: 2},
        {key: 'W', time: 2},

        {key: 'E', time: 4},
        {key: 'E', time: 4},
        {key: 'E', time: 4},
        {key: 'E', time: 4},

        {key: 'E', time: 4},
        {key: 'E', time: 1},
        {key: 'H', time: 1},
        {key: 'Q', time: 1},
        {key: 'E', time: 1},
        {key: 'G', time: 4},
        {key: 'J', time: 4},

        {key: 'J', time: 3},
        {key: 'U', time: 1},
        {key: 'Y', time: 3},
        {key: 'T', time: 1},
        {key: 'E', time: 4},
        {key: 'E', time: 4},

        {key: 'E', time: 4},
        {key: 'Y', time: 4},
        {key: 'W', time: 2},
        {key: 'W', time: 1},
        {key: 'E', time: 1},
        {key: 'W', time: 1},
        {key: '0', time: 1},
        {key: 'U', time: 2},
        {key: 'T', time: 2},

        {key: 'Y', time: 4},
        {key: '0', time: 4},
        {key: '0', time: 4},
        {key: '0', time: 2},
        {key: 'E', time: 2},

        // 17
        {key: 'Q', time: 1},
        {key: 'E', time: 1},
        {key: 'J', time: 1},
        {key: 'E', time: 1},
        {key: 'Q', time: 1},
        {key: 'E', time: 1},
        {key: 'W', time: 1},
        {key: 'E', time: 1},
        {key: 'U', time: 1},
        {key: 'J', time: 1},
        {key: 'Y', time: 1},
        {key: 'J', time: 1},
        {key: 'G', time: 2},
        {key: 'E', time: 1},
        {key: 'G', time: 1},

        {key: 'Y', time: 1},
        {key: 'Q', time: 1},
        {key: 'T', time: 1},
        {key: 'Q', time: 1},
        {key: 'Y', time: 1},
        {key: 'Q', time: 1},
        {key: 'Q', time: 1},
        {key: 'Q', time: 1},
        {key: 'T', time: 1},
        {key: 'Q', time: 1},
        {key: 'R', time: 1},
        {key: 'Q', time: 1},
        {key: 'E', time: 2},
        {key: 'E', time: 1},
        {key: 'T', time: 1},

        {key: 'R', time: 1},
        {key: 'H', time: 1},
        {key: 'E', time: 1},
        {key: 'H', time: 1},
        {key: 'E', time: 1},
        {key: 'D', time: 1},
        {key: 'W', time: 1},
        {key: 'D', time: 1},
        {key: 'Q', time: 1},
        {key: 'D', time: 1},
        {key: 'E', time: 1},
        {key: 'D', time: 1},

        {key: 'W', time: 1},
        {key: 'F', time: 1},
        {key: 'Q', time: 1},
        {key: 'F', time: 1},
        {key: 'H', time: 1},
        {key: 'F', time: 1},
        {key: 'H', time: 1},
        {key: 'F', time: 1},
        {key: 'F', time: 2},
        {key: 'F', time: 2},
        {key: 'D', time: 4},


    ],[
        {key: 'V', time: 2},
        {key: 'A', time: 2},
        {key: 'V', time: 2},
        {key: 'B', time: 2},
        {key: 'N', time: 4},
        {key: '0', time: 4},

        {key: 'B', time: 2},
        {key: 'S', time: 2},
        {key: 'B', time: 2},
        {key: 'N', time: 2},
        {key: 'J', time: 4},
        {key: '0', time: 4},

        {key: 'N', time: 2},
        {key: 'D', time: 2},
        {key: 'H', time: 2},
        {key: 'J', time: 2},
        {key: 'Q', time: 4},
        {key: '0', time: 4},

        {key: '0', time: 4},
        {key: '0', time: 4},
        {key: '0', time: 4},
        {key: '0', time: 4},

        {key: 'V', time: 2},
        {key: 'A', time: 2},
        {key: 'V', time: 2},
        {key: 'B', time: 2},
        {key: 'N', time: 4},
        {key: '0', time: 4},

        {key: 'B', time: 2},
        {key: 'S', time: 2},
        {key: 'B', time: 2},
        {key: 'N', time: 2},
        {key: 'J', time: 4},
        {key: '0', time: 4},

        {key: 'N', time: 2},
        {key: 'D', time: 2},
        {key: 'H', time: 2},
        {key: 'J', time: 2},
        {key: 'Q', time: 4},
        {key: '0', time: 4},

        {key: 'N', time: 4},
        {key: 'N', time: 4},
        {key: 'N', time: 4},
        {key: 'N', time: 4},

        {key: '0', time: 2},
        {key: 'A', time: 4},
        {key: '0', time: 2},
        {key: 'B', time: 2},
        {key: 'S', time: 2},
        {key: 'G', time: 4},

        {key: 'C', time: 2},
        {key: 'M', time: 2},
        {key: 'D', time: 2},
        {key: 'G', time: 2},
        {key: 'N', time: 2},
        {key: 'D', time: 2},
        {key: 'H', time: 2},
        {key: 'D', time: 2},

        {key: 'V', time: 2},
        {key: 'A', time: 2},
        {key: 'F', time: 2},
        {key: 'A', time: 2},
        {key: 'B', time: 2},
        {key: 'S', time: 2},
        {key: 'G', time: 2},
        {key: 'S', time: 2},

        {key: 'N', time: 2},
        {key: 'D', time: 2},
        {key: 'H', time: 2},
        {key: 'J', time: 2},
        {key: 'Q', time: 2},
        {key: 'D', time: 2},
        {key: 'H', time: 4},

        {key: 'V', time: 2},
        {key: 'A', time: 4},
        {key: '0', time: 2},
        {key: 'B', time: 2},
        {key: 'S', time: 2},
        {key: 'G', time: 4},

        {key: 'C', time: 2},
        {key: 'M', time: 2},
        {key: 'D', time: 4},
        {key: 'N', time: 2},
        {key: 'D', time: 2},
        {key: 'H', time: 4},

        {key: 'V', time: 2},
        {key: 'A', time: 2},
        {key: 'F', time: 4},
        {key: 'B', time: 2},
        {key: 'S', time: 2},
        {key: 'G', time: 4},

        {key: 'N', time: 2},
        {key: 'D', time: 2},
        {key: 'H', time: 2},
        {key: 'J', time: 2},
        {key: 'Q', time: 4},
        {key: '0', time: 4},


    ]
]

lemon =[[
    {key: '0', time: 4},
    {key: '0', time: 4},
    {key: '0', time: 4},
    {key: '0', time: 2},
    {key: 'Q', time: 1},
    {key: 'W', time: 1},

    {key: 'E', time: 2},
    {key: 'Q', time: 1},
    {key: 'H', time: 3},
    {key: 'W', time: 2},
    {key: 'J', time: 2},
    {key: 'G', time: 1},
    {key: 'D', time: 3},
    {key: 'J', time: 2},

    {key: 'H', time: 2},
    {key: 'G', time: 1},
    {key: 'A', time: 3},
    {key: 'G', time: 2},
    {key: 'D', time: 6},
    {key: 'S', time: 1},
    {key: 'D', time: 1},

    {key: 'N', time: 4},
    {key: 'F', time: 2},
    {key: 'J', time: 1},
    {key: 'Q', time: 1},
    {key: 'A', time: 4},
    {key: 'F', time: 2},
    {key: 'D', time: 1},
    {key: 'F', time: 1},

    {key: 'F', time: 4},
    {key: 'Q', time: 2},
    {key: 'J', time: 1},
    {key: 'H', time: 1},
    {key: 'D', time: 4},
    {key: '0', time: 2},
    {key: 'Q', time: 1},
    {key: 'W', time: 1},

    {key: 'E', time: 2},
    {key: 'Q', time: 1},
    {key: 'H', time: 3},
    {key: 'W', time: 2},
    {key: 'J', time: 2},
    {key: 'G', time: 1},
    {key: 'D', time: 3},
    {key: 'J', time: 2},

    {key: 'H', time: 2},
    {key: 'G', time: 1},
    {key: 'A', time: 3},
    {key: 'G', time: 2},
    {key: 'D', time: 6},
    {key: 'S', time: 1},
    {key: 'D', time: 1},

    {key: 'N', time: 4},
    {key: 'G', time: 2},
    {key: 'F', time: 1},
    {key: 'G', time: 1},
    {key: 'D', time: 2},
    {key: 'G', time: 2},
    {key: 'D', time: 2},
    {key: 'E', time: 2},

    {key: 'G', time: 2},
    {key: 'W', time: 1},
    {key: 'J', time: 2},
    {key: 'Q', time: 1},
    {key: 'Q', time: 8},





],[
    {key: '0', time: 4},
    {key: '0', time: 4},
    {key: '0', time: 4},
    {key: '0', time: 4},

    {key: 'N', time: 8},
    {key: 'B', time: 8},

    {key: 'V', time: 8},
    {key: 'Z', time: 8},

    {key: 'V', time: 8},
    {key: 'Z', time: 8},

    {key: 'Z', time: 8},
    {key: 'C', time: 2},
    {key: 'M', time: 2},
    {key: 'D', time: 4},


    {key: 'N', time: 2},
    {key: 'C', time: 2},
    {key: 'A', time: 4},
    {key: 'B', time: 2},
    {key: 'X', time: 2},
    {key: 'M', time: 4},

    {key: 'V', time: 2},
    {key: 'Z', time: 2},
    {key: 'N', time: 4},
    {key: 'Z', time: 2},
    {key: 'B', time: 2},
    {key: 'A', time: 4},

    {key: 'V', time: 2},
    {key: 'Z', time: 2},
    {key: 'N', time: 4},
    {key: 'Z', time: 2},
    {key: 'B', time: 2},
    {key: 'A', time: 4},

    {key: 'G', time: 2},
    {key: 'S', time: 2},
    {key: 'F', time: 4},
    {key: 'Z', time: 8},



    {key: '0', time: 4},
    {key: '0', time: 4},
    {key: '0', time: 4},
    {key: '0', time: 4},
    {key: '0', time: 4},
    {key: '0', time: 4},
    {key: '0', time: 4},
    {key: '0', time: 4},
    {key: '0', time: 4},
    {key: '0', time: 4},
    {key: '0', time: 4},
    {key: '0', time: 4},
    {key: '0', time: 4},
    {key: '0', time: 4},

]]
